# Generated by Django 3.0.6 on 2020-05-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WA_User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ukey', models.CharField(max_length=128, unique=True)),
                ('credential_id', models.CharField(max_length=250, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('pub_key', models.CharField(max_length=256, null=True, unique=True)),
                ('sign_count', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('rp_id', models.CharField(max_length=253)),
                ('icon_url', models.CharField(max_length=2083)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
