name: "Build and Deploy Docs"

on:
  push:
    branches: [ docs ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
            # Install a specific version of uv.
            version: "0.11.21"
            python-version: "3.12"
            enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
      
      - name: Build site
        run: |
          uv run make html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/html

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
